"""Action plan output schema.

Produced by the Action Plan Generator from organized ideas.
Tasks are concrete, priorities follow rules, no deadlines invented.
"""

from pydantic import BaseModel, Field

from idea_to_action.schemas.tasks import DraftCalendarEvent, DraftTask


class PlanResult(BaseModel):
    """A complete action plan generated from organized ideas.

    Contains broken-down tasks, calendar drafts, and summary.
    All tasks must be concrete and actionable.
    """

    summary: str = Field(
        ...,
        min_length=1,
        description="Concise summary of the action plan.",
    )
    tasks: list[DraftTask] = Field(
        default_factory=list,
        description="Concrete, actionable tasks with priority and effort.",
    )
    calendar_events: list[DraftCalendarEvent] = Field(
        default_factory=list,
        description="Suggested calendar events when dates are supported by evidence.",
    )
    missing_context: list[str] = Field(
        default_factory=list,
        description="What's still needed for better planning.",
    )
    is_inferred: bool = Field(
        default=True,
        description="True if all tasks/events were generated by the model.",
    )
